apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: customer-service
          imagePullPolicy: IfNotPresent
