apiVersion: v1
kind: Secret
metadata:
  name: customer-service-secret
type: Opaque
stringData:
  DB_PASSWORD: "postgres"
  RABBITMQ_USERNAME: "oficina"
  RABBITMQ_PASSWORD: "oficina"
  JWT_SECRET: "change-me-at-least-32-chars-long-for-production"
